### ISSUE TITLE
Apple can’t check app for malicious software.

### ISSUE THREAD

**Issue by yoshida-uji** [ryanslikesocool/AppLibrary#2]
## Operating System Info
macOS 13 Ventura

## App Library Version
Version 0.1.0

## Current Behavior
Apple Gatekeeper Rejected App Library, and say "Apple can’t check app for malicious software"
Please go through Apple's notary service.

![App_Libraray_block_gatekeeper](https://github.com/ryanslikesocool/AppLibrary/assets/85332240/3d363ebf-ac71-4651-87de-abc41a01485f)
![App_Libraray_block_gatekeeper2](https://github.com/ryanslikesocool/AppLibrary/assets/85332240/eb89ec01-6165-45fb-b309-c7374e5385fa)

**Comment by ryanslikesocool** [comment]
Apologies!  The mac app release process is new to me 😅
App Library is now notarized in the [0.1.1 release](https://github.com/ryanslikesocool/AppLibrary/releases/tag/0.1.1).
